export const countries = {
  Abkhazia: 'Абхазия',
  Australia: 'Австралия',
  Austria: 'Австрия',
  Azerbaijan: 'Азербайджан',
  'Aland Islands': 'Аландские острова',
  Albania: 'Албания',
  Algeria: 'Алжир',
  'American Samoa': 'Американское Самоа',
  Anguilla: 'Ангилья',
  Angola: 'Ангола',
  Andorra: 'Андорра',
  Antarctica: 'Антарктида',
  'Antigua and Barbuda': 'Антигуа и Барбуда',
  Argentina: 'Аргентина',
  Armenia: 'Армения',
  Aruba: 'Аруба',
  Afghanistan: 'Афганистан',
  Bahamas: 'Багамы',
  Bangladesh: 'Бангладеш',
  Barbados: 'Барбадос',
  Bahrain: 'Бахрейн',
  Belarus: 'Беларусь',
  Belize: 'Белиз',
  Belgium: 'Бельгия',
  Benin: 'Бенин',
  Bermuda: 'Бермуды',
  Bulgaria: 'Болгария',
  Bolivia: 'Боливия',
  'Bonaire, Sint Eustatius and Saba': 'Бонэйр, Саба и Синт-Эстатиус',
  'Bosnia and Herzegovina': 'Босния и Герцеговина',
  Botswana: 'Ботсвана',
  Brazil: 'Бразилия',
  'British Indian Ocean Territory': 'Британская территория в Индийском океане',
  'Brunei Darussalam': 'Бруней-Даруссалам',
  'Burkina Faso': 'Буркина-Фасо',
  Burundi: 'Бурунди',
  Bhutan: 'Бутан',
  Vanuatu: 'Вануату',
  Hungary: 'Венгрия',
  Venezuela: 'Венесуэла',
  'Virgin Islands, British': 'Виргинские острова, Британские',
  'Virgin Islands, U.S.': 'Виргинские острова, США',
  Vietnam: 'Вьетнам',
  Gabon: 'Габон',
  Haiti: 'Гаити',
  Guyana: 'Гайана',
  Gambia: 'Гамбия',
  Ghana: 'Гана',
  Guadeloupe: 'Гваделупа',
  Guatemala: 'Гватемала',
  Guinea: 'Гвинея',
  'Guinea-Bissau': 'Гвинея-Бисау',
  Germany: 'Германия',
  Guernsey: 'Гернси',
  Gibraltar: 'Гибралтар',
  Honduras: 'Гондурас',
  'Hong Kong': 'Гонконг',
  Grenada: 'Гренада',
  Greenland: 'Гренландия',
  Greece: 'Греция',
  Georgia: 'Грузия',
  Guam: 'Гуам',
  Denmark: 'Дания',
  Jersey: 'Джерси',
  Djibouti: 'Джибути',
  Dominica: 'Доминика',
  'Dominican Republic': 'Доминиканская Республика',
  Egypt: 'Египет',
  Zambia: 'Замбия',
  'Western Sahara': 'Западная Сахара',
  Zimbabwe: 'Зимбабве',
  Israel: 'Израиль',
  India: 'Индия',
  Indonesia: 'Индонезия',
  Jordan: 'Иордания',
  Iraq: 'Ирак',
  Iran: 'Иран',
  Ireland: 'Ирландия',
  Iceland: 'Исландия',
  Spain: 'Испания',
  Italy: 'Италия',
  Yemen: 'Йемен',
  'Cape Verde': 'Кабо-Верде',
  Kazakhstan: 'Казахстан',
  Cambodia: 'Камбоджа',
  Cameroon: 'Камерун',
  Canada: 'Канада',
  Qatar: 'Катар',
  Kenya: 'Кения',
  Cyprus: 'Кипр',
  Kyrgyzstan: 'Киргизия',
  Kiribati: 'Кирибати',
  China: 'Китай',
  'Cocos (Keeling) Islands': 'Кокосовые (Килинг) острова',
  Colombia: 'Колумбия',
  Comoros: 'Коморы',
  Congo: 'Конго',
  'Congo, Democratic Republic of the': 'Конго, Демократическая Республика',
  // eslint-disable-next-line quotes
  "Korea, Democratic People's Republic of Korea": 'Корея, Народно-Демократическая Республика',
  'Korea, Republic of Korea': 'Корея, Республика',
  'Costa Rica': 'Коста-Рика',
  // eslint-disable-next-line quotes
  "Cote d'Ivoire": "Кот д'Ивуар",
  Cuba: 'Куба',
  Kuwait: 'Кувейт',
  Curacao: 'Кюрасао',
  // eslint-disable-next-line quotes
  "Lao People's Democratic Republic": 'Лаос',
  Latvia: 'Латвия',
  Lesotho: 'Лесото',
  Liberia: 'Либерия',
  Lebanon: 'Ливан',
  Liechtenstein: 'Лихтенштейн',
  Libya: 'Ливия',
  Lithuania: 'Литва',
  Luxembourg: 'Люксембург',
  Mauritius: 'Маврикий',
  Mauritania: 'Мавритания',
  Madagascar: 'Мадагаскар',
  Mayotte: 'Майотта',
  Macau: 'Макао',
  Malawi: 'Малави',
  Malaysia: 'Малайзия',
  Mali: 'Мали',
  'United States Minor Outlying Islands': 'Малые Тихоокеанские отдаленные острова Соединенных Штатов',
  Maldives: 'Мальдивы',
  Malta: 'Мальта',
  Morocco: 'Марокко',
  Martinique: 'Мартиника',
  'Marshall Islands': 'Маршалловы острова',
  Mexico: 'Мексика',
  'Micronesia, Federated States of': 'Микронезия, Федеративные Штаты',
  Mozambique: 'Мозамбик',
  Moldova: 'Молдова',
  Monaco: 'Монако',
  Mongolia: 'Монголия',
  Montserrat: 'Монтсеррат',
  Burma: 'Мьянма',
  Namibia: 'Намибия',
  Nauru: 'Науру',
  Nepal: 'Непал',
  Niger: 'Нигер',
  Nigeria: 'Нигерия',
  Netherlands: 'Нидерланды',
  Nicaragua: 'Никарагуа',
  Niue: 'Ниуэ',
  'New Zealand': 'Новая Зеландия',
  'New Caledonia': 'Новая Каледония',
  Norway: 'Норвегия',
  'United Arab Emirates': 'Объединенные Арабские Эмираты',
  Oman: 'Оман',
  'Bouvet Island': 'Остров Буве',
  'Isle of Man': 'Остров Мэн',
  'Norfolk Island': 'Остров Норфолк',
  'Christmas Island': 'Остров Рождества',
  'Heard Island and McDonald Islands': 'Остров Херд и острова Макдональд',
  'Cayman Islands': 'Острова Кайман',
  'Cook Islands': 'Острова Кука',
  'Turks and Caicos Islands': 'Острова Теркс и Кайкос',
  Pakistan: 'Пакистан',
  Palau: 'Палау',
  'Palestinian Territory, Occupied': 'Палестина, государство',
  Panama: 'Панама',
  'Holy See (Vatican City State)': 'Папский Престол (Государство — город Ватикан)',
  'Papua New Guinea': 'Папуа-Новая Гвинея',
  Paraguay: 'Парагвай',
  Peru: 'Перу',
  Pitcairn: 'Питкерн',
  Poland: 'Польша',
  Portugal: 'Португалия',
  'Puerto Rico': 'Пуэрто-Рико',
  Macedonia: 'Республика Македония',
  Romania: 'Румыния',
  Reunion: 'Реюньон',
  Russia: 'Россия',
  Rwanda: 'Руанда',
  Samoa: 'Самоа',
  'San Marino': 'Сан-Марино',
  'Sao Tome and Principe': 'Сан-Томе и Принсипи',
  'Saudi Arabia': 'Саудовская Аравия',
  'Saint Helena, Ascension And Tristan Da Cunha': 'Святая Елена, Остров вознесения, Тристан-да-Кунья',
  'Northern Mariana Islands': 'Северные Марианские острова',
  Serbia: 'Сербия',
  Seychelles: 'Сейшелы',
  'Saint Barthelemy': 'Сен-Бартелеми',
  'Saint Martin (French Part)': 'Сен-Мартен (французская часть)',
  'Saint Martin (Netherlands Part)': 'Сен-Мартен (нидерланская часть)',
  Senegal: 'Сенегал',
  'Saint Vincent and the Grenadines': 'Сент-Винсент и Гренадины',
  'Saint Kitts and Nevis': 'Сент-Китс и Невис',
  'Saint Lucia': 'Сент-Люсия',
  'Saint Pierre and Miquelon': 'Сент-Пьер и Микелон',
  Singapore: 'Сингапур',
  'Syrian Arab Republic': 'Сирийская Арабская Республика',
  Slovakia: 'Словакия',
  Slovenia: 'Словения',
  'United Kingdom': 'Соединенное Королевство Британии',
  'United States': 'Соединенные Штаты Америки',
  'Solomon Islands': 'Соломоновы острова',
  Somalia: 'Сомали',
  Sudan: 'Судан',
  Suriname: 'Суринам',
  'Sierra Leone': 'Сьерра-Леоне',
  Tajikistan: 'Таджикистан',
  Thailand: 'Таиланд',
  'Taiwan, Province of China': 'Тайвань (Китай)',
  Tanzania: 'Танзания',
  'Timor-Leste': 'Тимор-Лесте',
  Togo: 'Того',
  Tokelau: 'Токелау',
  Tonga: 'Тонга',
  'Trinidad and Tobago': 'Тринидад и Тобаго',
  Tuvalu: 'Тувалу',
  Tunisia: 'Тунис',
  Turkmenistan: 'Туркмения',
  Turkey: 'Турция',
  Uganda: 'Уганда',
  Uzbekistan: 'Узбекистан',
  Ukraine: 'Украина',
  'Wallis and Futuna': 'Уоллис и Футуна',
  Uruguay: 'Уругвай',
  'Faroe Islands': 'Фарерские острова',
  Fiji: 'Фиджи',
  Philippines: 'Филиппины',
  Finland: 'Финляндия',
  'Falkland Islands (Malvinas)': 'Фолклендские острова (Мальвинские)',
  France: 'Франция',
  'French Guiana': 'Французская Гвиана',
  'French Polynesia': 'Французская Полинезия',
  'French Southern Territories': 'Французские Южные территории',
  Croatia: 'Хорватия',
  'Central African Republic': 'Центрально-Африканская Республика',
  Chad: 'Чад',
  Montenegro: 'Черногория',
  'Czech Republic': 'Чешская Республика',
  Chile: 'Чили',
  Switzerland: 'Швейцария',
  Sweden: 'Швеция',
  'Svalbard and Jan Mayen': 'Шпицберген и Ян Майен',
  'Sri Lanka': 'Шри-Ланка',
  Ecuador: 'Эквадор',
  'Equatorial Guinea': 'Экваториальная Гвинея',
  'El Salvador': 'Эль-Сальвадор',
  Eritrea: 'Эритрея',
  Eswatini: 'Эсватини',
  Estonia: 'Эстония',
  Ethiopia: 'Эфиопия',
  'South Africa': 'Южная Африка',
  'South Georgia and the South Sandwich Islands': 'Южная Джорджия и Южные Сандвичевы острова',
  'South Ossetia': 'Южная Осетия',
  'South Sudan': 'Южный Судан',
  Jamaica: 'Ямайка',
  Japan: 'Япония',
} as const;

export type CountryKey = keyof typeof countries;
