/* eslint-disable @typescript-eslint/no-require-imports */
const {createThemes} = require('tw-colors');

const figmaVariablesParsingFolder = __dirname + '/src/styles/generated/';

const {width, height, 'min-height': minHeight, 'min-width': minWidth, spacing, ...theme} = require(
  `${figmaVariablesParsingFolder}tailwindTheme.json`,
);

/** @type {import('tailwindcss').Config} */
const config = {
  content: ['./src/**/*.{html,ts,tsx}', '.storybook/preview.tsx'],
  darkMode: 'class',
  theme: {
    /** 1. Зануляем все встроенные цвета */
    colors: {},

    /** 3. Разрешаем только те элементы, которые нам нужны */
    ...theme,

    extend: {width, height, minHeight, minWidth, spacing},
  },
  plugins: [
    createThemes(
      {
        /** 2. Импортируем только наши сгенерированные цвета из фигмы */
        light: require(`${figmaVariablesParsingFolder}tailwindLightColors.json`),
        dark: require(`${figmaVariablesParsingFolder}tailwindDarkColors.json`),
      },
      {
        defaultTheme: 'light',
      },
    ),
    require('./scripts/customCSSPlugin'),
  ],
  corePlugins: {
    /** 5. Выключаем normalize */
    preflight: false,

    /**
     * 4. Выключаем все встроенные варианты в tailwind.
     * Включаем только нужные с помощью комментирования - так нагляднее!
     */
    accentColor: false,
    // animation: false,
    aria: false,
    aspectRatio: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    // backgroundColor: false,
    backgroundImage: false,
    backgroundOpacity: false,
    // backgroundPosition: false,
    backgroundSize: false,
    blur: false,
    // borderColor: false,
    borderOpacity: false,
    // borderRadius: false,
    borderSpacing: false,
    // borderWidth: false,
    // boxShadow: false,
    // boxShadowColor: false,
    brightness: false,
    // caretColor: false,
    colors: false,
    columns: false,
    container: false,
    // content: false,
    contrast: false,
    // cursor: false,
    divideColor: false,
    divideOpacity: false,
    divideWidth: false,
    dropShadow: false,
    // fill: false,
    // flex: false,
    // flexBasis: false,
    // flexGrow: false,
    // flexShrink: false,
    fontFamily: false,
    fontSize: false,
    fontWeight: false,
    // gap: false,
    gradientColorStops: false,
    gradientColorStopPositions: false,
    grayscale: false,
    // gridAutoColumns: false,
    // gridAutoRows: false,
    // gridColumn: false,
    // gridColumnEnd: false,
    // gridColumnStart: false,
    // gridRow: false,
    // gridRowEnd: false,
    // gridRowStart: false,
    // gridTemplateColumns: false,
    // gridTemplateRows: false,
    // height: false,
    hueRotate: false,
    //inset: false,
    invert: false,
    keyframes: false,
    letterSpacing: false,
    lineHeight: false,
    listStyleType: false,
    listStyleImage: false,
    // margin: false,
    // lineClamp: false,
    // maxHeight: false,
    // maxWidth: false,
    // minHeight: false,
    // minWidth: false,
    // objectPosition: false,
    // opacity: false,
    order: false,
    // outlineColor: false,
    outlineOffset: false,
    outlineWidth: false,
    // padding: false,
    placeholderColor: false,
    placeholderOpacity: false,
    ringColor: false,
    ringOffsetColor: false,
    ringOffsetWidth: false,
    ringOpacity: false,
    ringWidth: false,
    // rotate: false,
    saturate: false,
    // scale: false,
    screens: false,
    scrollMargin: false,
    scrollPadding: false,
    sepia: false,
    skew: false,
    space: false,
    // spacing: false,
    // stroke: false,
    strokeWidth: false,
    supports: false,
    data: false,
    // textColor: false,
    textDecorationColor: false,
    textDecorationThickness: false,
    textIndent: false,
    textOpacity: false,
    textUnderlineOffset: false,
    // transformOrigin: false,
    // transitionDelay: false,
    // transitionDuration: false,
    // transitionProperty: false,
    // transitionTimingFunction: false,
    // translate: false,
    // width: false,
    willChange: false,
    //zIndex: false,
  },
};

module.exports = config;
